### PR TITLE
Clean up stale connections when an on-premise connector connects or reconnects

### PR DESCRIPTION
**Pull request by jasminsehic**
https://github.com/thinktecture/relayserver/issues/98

### CODE REVIEW

**Comment by thomashilzendegen** [comment]
Thank you for your contribution.

Unfortunately this breaks the support for having multiple relay servers and also having multiple on-premise services connecting. But if this works for you, I would suggest to have this code in your fork only. Sorry for closing this pull request.

**Comment by jasminsehic** [comment]
Hi @thomashilzendegen, are you able to elaborate a bit more on how this breaks having multiple relay servers since we will be doing that soon as well.

I understood that there is only one on-premise service (per link) so even if there are multiple relay servers it would only connect to one relay server at a time? Not sure what the use case is for mutliple on-premise services with the same link? Is it for hosting different on-premise targets on different servers?

**Comment by thomashilzendegen** [comment]
Hi @jasminsehic, the purpose for having multiple on-premise services is to use the automatic round robin balancing by RabbitMQ, because all on-premise services of one link are consuming the same queue. In that case some kind of load-balancing could be achieved when the on-premise service is doing more than just forwarding the request to an API.

**Comment by gingters** [comment]
Hi @jasminsehic additionally, fortunately you can have multiple on-premise connectors (OPC) for one link, and they can be active at once. This is for both load balancing between the both as Thomas mentioned (round robin fetching of the messages) as well as fault tolerance. In case one of the OPCs crashes, the other is still connected and will continue to process requests.

Also, when having multiple relay servers in a multi-node environment behind a load balancer it is not guaranteed that a OPC will always reconnect to the same relay server instance. So keeping the active connection in memory on a single relay server node, as you proposed, would unfortunately not work while an OPC disconnects for a short amount of time and reconnects to another relay server node.

**Comment by jasminsehic** [comment]
Hi @thomashilzendegen & @gingters that makes sense, thank you for responding.

How do you suggest I deal with the issue I am seeing from the client application side when the OPC ungracefully disconnects and connects again leaving two active connection id's in place while really only one is active? When this happens the client application gets a 504 HTTP status code response on every second call and every other call in between it gets the expected response. So I am seeing this:

Call #1. 504 http status code
Call #2 200 http status code
Call #3. 504 http status code
Call #4. 200 http status code

I suspect it is due to this automatic round robin nature of RabbitMQ but from a client application perspective this is not a great. Ideally I would like to remove the stale connection without destroying any other connections that may be present on the same RelayServer instance or another instance if it is behind a load balancer. Is there a way perhaps to not destroy the entire queue for the link but to somehow just unregister the stale connection if from RabbitMQ?

**Comment by gingters** [comment]
@jasminsehic
If you know of a way how we can reliably detect that a connection is stale in a backwards-compatible manner (i.e. OPC v1 does not support heartbeats), we could remove that from the queue.
We must make 100% sure we don't have a false positive and remove an active connection.

**Comment by jasminsehic** [comment]
@gingters let me see what I can do. Can you please confirm that for multiple relay servers behind a load balancer that RabbitMQ needs to be shared between them or each instance needs its own RabbitMQ instance? Not clear on this. Thanks.

**Comment by gingters** [comment]
Hi @jasminsehic ,
the rabbit is shared between the server instances, so that all relay servers write to and read from the same queues. To be more failure resistant, it would however be best to use a rabbit cluster and have the relay servers connect to different rabbit nodes.

**Comment by jasminsehic** [comment]
@gingters please see #104 for second attempt at this hotfix.

**Comment by jasminsehic** [comment]
@gingters I finally got around setting up multiple rabbit nodes. I do get an exception during publish for some reason. Is there a particular way I have to setup multiple rabbit nodes? I get:

`2018-03-14 05:35:23.291 +00:00 [Error] Action: "ClientController"."none", Request: "GET": http://relayserverdev2.helix-playground.net/relay/audev13/api/embed-api/1.0/time.
RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - unknown delivery tag 1", classId=60, methodId=80, cause=
   at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
   at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Impl.ModelBase.BasicPublish(String exchange, String routingKey, Boolean mandatory, IBasicProperties basicProperties, Byte[] body)`

**Comment by jasminsehic** [comment]
Looks like this is a load balancer related issue where acknowledge went to another RelayServer instance. Have to find a way to make the connector connections sticky.

**Comment by jasminsehic** [comment]
Fixed with https://github.com/thinktecture/relayserver/pull/107

**Pull request closed without merging**
