### PR TITLE
Add docker compose for sample implementation

### PR DESCRIPTION
**Pull request by ThorstenHans**

### CODE REVIEW

**Comment by ThorstenHans** [comment]
Worth mentioning that a useful configuration for the connector is still missing (don't know what to provide as useful target here 😄 )

**Comment by gingters** [comment]
There are a few issues with this.
First, dependencies aren't correct. Management & statistics API don't need rabbit, only the db and the migrations. All services log to seq so that should be a dependency for all except db and rabbit. Server needs db, rabbit, seq and idsrv. Connector needs idsrv and relay server.
Seq default port is 5341 (we have a zahlendreher somewhere)

Besides that and the missing Connector config (which is somewhat important for a sample), there is currently no concept of adding the tenant to the database. Since a relay server should not come with any default user / tenant config that should not be part of the migrations. Migrations only provide an empty database scheme.

We need some way to execute a http call against the management API to add a tenant for the connector while spinning up, OR execute a SQL statement, both after the migrations ran.

I can correct the dependencies and ports myself, but I need some input on how to call the API or execute the SQL statement after migrations ran and before the connector starts, @ThorstenHans .

**Comment by ThorstenHans** [comment]
@gingters Seq Port mapping is exactly the same as it was in your `run-dependencies` powershell thing.

Dependencies in docker-compose are composed into a dependency tree, however there was a mis configuration with the dependencies which I will fix in a minute.

Regarding configuration and data-seeding: That's what I mentioned in the PR comment. Those things are missing because I don't know what makes sense from a functional point of view. Technically, you should consider providing a dedicated container that get executed when bootstrapping the environment. Because that container is deployed to the same docker-network, It can basically interact with every service in the same network.

**Comment by thomashilzendegen** [comment]
I am not sure what the current state of this PR is. It seems that the dependencies still aren't right.

The idea of an bootstrapping container sounds very nice to me.

**Comment by gingters** [comment]
Okay, re-did a bit. 😁
Ports and dependencies are now correct. Migrations and initial seed of Tenants are done.

We now have a complete environment with a 2-node RabbitMq cluster, one DB, one Seq, one Management API, one IdSrv, two RelayServer and 4 connectors, all started with a single `docker compose up`.

**Comment by thomashilzendegen** [comment]
Closed in favour of #433

**Pull request closed without merging**
