### PR TITLE
Added English documentation

### PR DESCRIPTION
**Pull request by jasminsehic**

### CODE REVIEW

**Comment by gingters** [comment]
Thank you for helping out with the English documentation!
We are currently a bit busy, but by now it seems that we could get around reviewing the PR around end of next week. So please be a bit patient ;)

**Comment by jasminsehic** [comment]
@gingters no problems, you have built an incredibly valuable application. Happy to help.

**Comment by thomashilzendegen** [comment]
Hi @jasminsehic,

thanks for your changes. Would you be so kind to recreate the branch and cherry pick the commits (4425912, 60a7d3d, c76bd99, 335e837, 3fd1646) and update your PR by a force push? We had to do some cleanings on our develop branch and thus, this PR cannot be merged now.

**Comment by jasminsehic** [comment]
@thomashilzendegen I've cherry picked as requested.

**Comment by thomashilzendegen** [comment]
Perfect! Thanks.

**Pull request merged**
