### PR TITLE
Added support for Memcached as a shared temporary request store

### PR DESCRIPTION
**Pull request by jasminsehic**

### CODE REVIEW

**Comment by thomashilzendegen** [comment]
Thank you for your contribution.

Unfortunately is this something very specific to your usecase and it is adding references to 3rd party libraries the project should not have. We are currently discussing the move of the extension possibility for a different store into the custom code assembly. Sorry for closing this pull request.

**Comment by jasminsehic** [comment]
@thomashilzendegen I am using a fork at the moment with this feature. I'd be happy to contribute to a plugin approach if you have particular idea or approach in mind?

**Comment by gingters** [comment]
We are thinking about ways to allow to provide these kind of extensions in separate repositories / projects. A user should be able to put the resulting .dll alongside the .exe and configure it, so that it can be picked up at runtime. That would mean changing the way the store(s) are added to the DI and how they are configured.

By 'we are thinking' I mean that Thomas and I talked only *very briefly* about that, and we don't yet have aany plan on how that could look like. I also can't say how high of a priority that would get, when we would put that on a roadmap, as that involves some other colleague.

Sorry to be that vague, but we only have very limited time that we can allocate to RelayServer, and at the moment a few things have higher priority.

**Comment by jasminsehic** [comment]
@gingters no problems, thanks for the reply. I think I can put something like that together soon. No expectation for you to accept it though.

**Comment by jasminsehic** [comment]
@gingters I have made data stores something that can be injected from custom code assembly now in #109

**Pull request closed without merging**
