### PR TITLE
Added Uri to InterceptedRequest to allow interceptors to insert Forwarded header

### PR DESCRIPTION
**Pull request by jasminsehic**
Replacement for #47

### CODE REVIEW

**Comment by gingters** [comment]
Hello Jasmine,

thank you for your PR. This is looking good.

We currently have a bit of a bigger change pending as you can probably see in our PR list (especially switching from NLog to Serilog) and some other changes based upon this bigger change. So if we would merge this now, we would need to amend the other PR and do quite some bit of additional rebasing, so we'd like to wait a bit until the bigger changes are merged before merging your PR, as we then only need to switch to logging around to Serilog and are done. So please, bear a bit with us. Thanks for your patience ;)

**Comment by jasminsehic** [comment]
@gingters no problems, let me know if you want me to rebase against anything in particular earlier to make sure this branch ends up in a mergeable state at the end.

**Comment by jasminsehic** [comment]
I have only added the necessary changes to allow interceptors to be aware of the original request uri so that they can do things like insert Forwarded headers. I can add the Forwarded Header Interceptor as a separate PR if you like.

**Comment by jasminsehic** [comment]
I have only added the necessary changes to allow interceptors to be aware of the original request uri so that they can do things like insert Forwarded headers. I can add the Forwarded Header Interceptor as a separate PR if you like.

**Comment by gingters** [comment]
Replaced by #131, we renamed the property to ClientRequestUri instead of Uri only. Will be released in 2.1 (soon)

**Pull request closed without merging**
